-- Supabase PostgreSQL Migration Script & Seed Data
-- Run this in your Supabase Project SQL Editor

-- --------------------------------------------------------
-- 1. Create Tables
-- --------------------------------------------------------

CREATE TABLE IF NOT EXISTS portfolio_profile (
  id INT PRIMARY KEY DEFAULT 1,
  full_name VARCHAR(160) NOT NULL,
  headline VARCHAR(255) NOT NULL,
  bio TEXT,
  email VARCHAR(180),
  phone VARCHAR(60),
  location VARCHAR(180),
  map_embed_url TEXT,
  github_url VARCHAR(500),
  linkedin_url VARCHAR(500),
  resume_url VARCHAR(500),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT one_profile CHECK (id = 1)
);

CREATE TABLE IF NOT EXISTS site_sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section_key VARCHAR(50) NOT NULL UNIQUE,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  media JSONB DEFAULT '[]'::jsonb,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_section_key CHECK (section_key IN ('intro', 'about', 'contact'))
);

CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) UNIQUE,
  description TEXT,
  tech_stack JSONB DEFAULT '[]'::jsonb,
  media JSONB DEFAULT '[]'::jsonb,
  live_url VARCHAR(500),
  repo_url VARCHAR(500),
  featured BOOLEAN DEFAULT FALSE,
  status VARCHAR(50) DEFAULT 'published',
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_project_status CHECK (status IN ('draft', 'published'))
);

CREATE TABLE IF NOT EXISTS certificates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  issuer VARCHAR(180),
  issued_at DATE,
  credential_id VARCHAR(180),
  credential_url VARCHAR(500),
  description TEXT,
  media JSONB DEFAULT '[]'::jsonb,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uniq_certificate UNIQUE (title, issuer)
);

CREATE TABLE IF NOT EXISTS courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  provider VARCHAR(180),
  description TEXT,
  started_at DATE,
  completed_at DATE,
  link VARCHAR(500),
  media JSONB DEFAULT '[]'::jsonb,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uniq_course UNIQUE (title, provider)
);

CREATE TABLE IF NOT EXISTS education (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institution VARCHAR(255) NOT NULL,
  degree VARCHAR(255),
  field_of_study VARCHAR(255),
  start_year SMALLINT,
  end_year SMALLINT,
  description TEXT,
  link VARCHAR(500),
  media JSONB DEFAULT '[]'::jsonb,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uniq_education UNIQUE (institution, degree, field_of_study)
);

-- --------------------------------------------------------
-- 2. Setup Updated At Triggers
-- --------------------------------------------------------

CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_portfolio_profile_modtime ON portfolio_profile;
CREATE TRIGGER update_portfolio_profile_modtime BEFORE UPDATE ON portfolio_profile FOR EACH ROW EXECUTE FUNCTION update_modified_column();

DROP TRIGGER IF EXISTS update_site_sections_modtime ON site_sections;
CREATE TRIGGER update_site_sections_modtime BEFORE UPDATE ON site_sections FOR EACH ROW EXECUTE FUNCTION update_modified_column();

DROP TRIGGER IF EXISTS update_projects_modtime ON projects;
CREATE TRIGGER update_projects_modtime BEFORE UPDATE ON projects FOR EACH ROW EXECUTE FUNCTION update_modified_column();

DROP TRIGGER IF EXISTS update_certificates_modtime ON certificates;
CREATE TRIGGER update_certificates_modtime BEFORE UPDATE ON certificates FOR EACH ROW EXECUTE FUNCTION update_modified_column();

DROP TRIGGER IF EXISTS update_courses_modtime ON courses;
CREATE TRIGGER update_courses_modtime BEFORE UPDATE ON courses FOR EACH ROW EXECUTE FUNCTION update_modified_column();

DROP TRIGGER IF EXISTS update_education_modtime ON education;
CREATE TRIGGER update_education_modtime BEFORE UPDATE ON education FOR EACH ROW EXECUTE FUNCTION update_modified_column();

-- --------------------------------------------------------
-- 3. Populate Seed Data
-- --------------------------------------------------------

-- Portfolio Profile
INSERT INTO portfolio_profile (id, full_name, headline, bio, email, phone, location, map_embed_url, github_url, linkedin_url, resume_url)
VALUES (
  1,
  'Biman Mandal',
  'Senior Web Developer',
  'I am a Senior Software Developer with 4+ years of experience in designing, developing, and maintaining scalable web applications and APIs. Currently working as a Lead Backend Developer, I specialize in Node.js (Express.js), TypeScript, MongoDB, PHP (Laravel), and MySQL, with hands-on experience across full-stack technologies.',
  'bimanm193@gmail.com',
  '+91 62940 67811',
  'Kolkata, West Bengal, India',
  'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3684.093557088927!2d88.363895!3d22.572646!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3adc8b5dfbefffff%3A0x1d4e0e5a6f2ea8b0!2sKolkata%2C%20West%20Bengal%2C%20India!5e0!3m2!1sen!2sin!4v1700000000000!5m2!1sen!2sin',
  'https://github.com/im-bimanmandal',
  'https://www.linkedin.com/in/im-bimanmandal',
  '#'
) ON CONFLICT (id) DO UPDATE SET
  full_name = EXCLUDED.full_name,
  headline = EXCLUDED.headline,
  bio = EXCLUDED.bio,
  email = EXCLUDED.email,
  phone = EXCLUDED.phone,
  location = EXCLUDED.location,
  map_embed_url = EXCLUDED.map_embed_url,
  github_url = EXCLUDED.github_url,
  linkedin_url = EXCLUDED.linkedin_url,
  resume_url = EXCLUDED.resume_url;

-- Site Sections
INSERT INTO site_sections (section_key, title, description, media, sort_order)
VALUES
('intro', 'Biman Mandal', 'Senior Web Developer & Lead Backend Developer building high-performance APIs, scalable database architectures, and production-ready applications with Laravel, Node.js, and React.', '[]'::jsonb, 1),
('about', 'About Me', 'I am a Senior Software Developer with 4+ years of experience. I specialize in designing and maintaining scalable backend systems, database schemas, and clean frontend integrations using PHP/Laravel, Node.js (Express), MongoDB, and MySQL.', '[]'::jsonb, 2),
('contact', 'Contact', 'Email: bimanm193@gmail.com | Phone: +91 62940 67811', '[]'::jsonb, 7)
ON CONFLICT (section_key) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  media = EXCLUDED.media,
  sort_order = EXCLUDED.sort_order;

-- Projects
INSERT INTO projects (id, title, slug, description, tech_stack, media, live_url, repo_url, featured, status, sort_order)
VALUES
(12, 'OCHats', 'ochats', 'Omnichannel Customer Communication CRM SaaS allowing businesses to manage customer conversations across 14+ messaging platforms (WhatsApp, Messenger, Instagram, LINE, WeChat, Email) from a single inbox. Features visual drag-and-drop workflow builders (Drawflow), timezone-aware queue broadcasts, contact intelligence/merging, and Stripe subscription systems.', '["Laravel", "PHP", "MySQL", "Livewire", "Redis", "Stripe"]'::jsonb, '[{"url": "/uploads/ochats.png", "name": "ochats.png", "type": "image"}]'::jsonb, 'https://www.app.ochats.io/', '#', TRUE, 'published', 1),
(13, 'Runway Hive', 'runway-hive', 'Global fashion-tech portal and e-commerce marketplace connecting models, designers, and photographers. Features advanced profile management, points-based rewards economy (gamification), multi-step job board and hiring dashboards, location-aware filters, and secure payments via Stripe and PayPal.', '["Next.js", "React", "Node.js", "MongoDB", "Mongoose", "Stripe", "PayPal"]'::jsonb, '[{"url": "/uploads/runwayhive.png", "name": "runwayhive.png", "type": "image"}]'::jsonb, 'https://runwayhive.com/', '#', TRUE, 'published', 2),
(14, 'Maneuver', 'maneuver', 'On-demand courier delivery shipment platform featuring multi-stop route optimization, real-time GPS tracking (Socket.IO + Redis), intelligent proximity driver matching, dynamic pricing, and Stripe Identity document verification.', '["Node.js", "Express", "MySQL", "Sequelize", "Socket.io", "Redis", "Stripe Connect"]'::jsonb, '[{"url": "/uploads/maneuver.png", "name": "maneuver.png", "type": "image"}]'::jsonb, 'https://maneuver.live', '#', TRUE, 'published', 3),
(15, 'ACC – SaaS Learning Management System', 'acc-lms', 'A SaaS-based education management ecosystem with Web app, mobile app, and admin portal enabling schools to manage students, courses, batches, attendance, exams, assignments, fees, results, and notifications.', '["Laravel", "Livewire", "MySQL", "Bootstrap"]'::jsonb, '[{"url": "/uploads/acc_lms.png", "name": "acc_lms.png", "type": "image"}]'::jsonb, '#', '#', TRUE, 'published', 4),
(16, 'Ayan Chakraborty Classes LMS', 'ayan-classes', 'Coaching institute Learning Management System featuring custom Zoom API live class scheduling, media video hosting on AWS S3 & Cloudflare R2, SMS alerts via Vonage, dynamic PDF assignments, and school reporting tools.', '["Laravel 12", "Livewire 3", "Tailwind CSS", "Alpine.js", "AWS S3", "Cloudflare R2"]'::jsonb, '[{"url": "/uploads/ayanclasses.png", "name": "ayanclasses.png", "type": "image"}]'::jsonb, 'https://admin.ayanchakrabortyclasses.co.in/admin/login', '#', TRUE, 'published', 5),
(17, 'Leroi Lead Operations Platform', 'leroi', 'Enterprise lead and operations management platform streamlining lead tracking, workflow automation, customer engagement, visual pipeline dashboards, team communication, and automated sales reporting.', '["Laravel", "Livewire", "PHP", "Tailwind CSS", "MySQL"]'::jsonb, '[{"url": "/uploads/leroi.png", "name": "leroi.png", "type": "image"}]'::jsonb, '#', '#', TRUE, 'published', 6)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  slug = EXCLUDED.slug,
  description = EXCLUDED.description,
  tech_stack = EXCLUDED.tech_stack,
  media = EXCLUDED.media,
  live_url = EXCLUDED.live_url,
  repo_url = EXCLUDED.repo_url,
  featured = EXCLUDED.featured,
  status = EXCLUDED.status,
  sort_order = EXCLUDED.sort_order;

-- Certificates
INSERT INTO certificates (id, title, issuer, issued_at, credential_id, credential_url, description, media, sort_order)
VALUES
(6, 'Lead Backend Developer Certification', 'Inforoot Solution', '2025-09-01', 'LEAD-BEND-09', '#', 'Recognition of leading backend architecture, REST API design, and system engineering.', '[]'::jsonb, 1),
(7, 'SaaS Architecture & Project Delivery', 'Notebrains Software', '2025-03-01', 'SAAS-PROJ-03', '#', 'Design and delivery of multi-tenant platforms, socket tracking, and billing integrations.', '[]'::jsonb, 2)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  issuer = EXCLUDED.issuer,
  issued_at = EXCLUDED.issued_at,
  credential_id = EXCLUDED.credential_id,
  credential_url = EXCLUDED.credential_url,
  description = EXCLUDED.description,
  media = EXCLUDED.media,
  sort_order = EXCLUDED.sort_order;

-- Courses
INSERT INTO courses (id, title, provider, description, started_at, completed_at, link, media, sort_order)
VALUES
(7, 'Omnichannel Message Routing Systems', 'Internal Training', 'Architecting multi-platform message normalization engines and webhook handlers.', '2024-01-01', '2024-03-01', '#', '[]'::jsonb, 1),
(8, 'Real-time Socket.io & Redis Caching', 'Advanced Technical Hub', 'Deploying Redis cache to minimize database hits in high-frequency location queries.', '2023-06-01', '2023-08-01', '#', '[]'::jsonb, 2)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  provider = EXCLUDED.provider,
  description = EXCLUDED.description,
  started_at = EXCLUDED.started_at,
  completed_at = EXCLUDED.completed_at,
  link = EXCLUDED.link,
  media = EXCLUDED.media,
  sort_order = EXCLUDED.sort_order;

-- Education
INSERT INTO education (id, institution, degree, field_of_study, start_year, end_year, description, link, media, sort_order)
VALUES
(5, 'Techno India (Hooghly Campus)', 'Bachelor of Computer Application (BCA)', 'Computer Application', 2017, 2020, 'Acquired base computer science knowledge, relational databases, web scripting languages, and application development fundamentals.', 'https://admin.ayanchakrabortyclasses.co.in/', '[]'::jsonb, 1)
ON CONFLICT (id) DO UPDATE SET
  institution = EXCLUDED.institution,
  degree = EXCLUDED.degree,
  field_of_study = EXCLUDED.field_of_study,
  start_year = EXCLUDED.start_year,
  end_year = EXCLUDED.end_year,
  description = EXCLUDED.description,
  link = EXCLUDED.link,
  media = EXCLUDED.media,
  sort_order = EXCLUDED.sort_order;

-- --------------------------------------------------------
-- 4. Reset Identity Sequences
-- --------------------------------------------------------

SELECT setval(pg_get_serial_sequence('site_sections', 'id'), COALESCE((SELECT MAX(id) FROM site_sections), 1));
SELECT setval(pg_get_serial_sequence('projects', 'id'), COALESCE((SELECT MAX(id) FROM projects), 1));
SELECT setval(pg_get_serial_sequence('certificates', 'id'), COALESCE((SELECT MAX(id) FROM certificates), 1));
SELECT setval(pg_get_serial_sequence('courses', 'id'), COALESCE((SELECT MAX(id) FROM courses), 1));
SELECT setval(pg_get_serial_sequence('education', 'id'), COALESCE((SELECT MAX(id) FROM education), 1));
